# Generated by Django 2.0.5 on 2018-05-28 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS')], default='PENDING', max_length=50, verbose_name='state')),
                ('report', models.URLField()),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metricsapp.Metric')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metricsapp.Page')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='reports',
            field=models.ManyToManyField(through='metricsapp.Report', to='metricsapp.Metric'),
        ),
    ]
