# Generated by Django 2.0.5 on 2018-05-28 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metricsapp', '0002_auto_20180528_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-status_date']},
        ),
    ]
