# Generated by Django 2.0.5 on 2018-05-31 19:51

from django.db import migrations


class Migration(migrations.Migration):
    PAGES = [('http://www.rsagroup.bh','RSA Bahrain'),
             ('http://be.rsagroup.com','RSA BELGIUM'),
             ('https://www1.johnson.ca','Johnson Insurance'),
             ('https://www.rsagroup.ca','RSA Canada'),
             ('https://www.rsatravelinsurance.com','RSA Travel Insurance'),
             ('https://www.codan.dk','Rejseforsikring'),
             ('http://fr.rsagroup.com','RSA France'),
             ('http://de.rsagroup.com','RSA Deutschland'),
             ('https://www.123.ie','123.ie'),
             ('https://www.rsagroup.ie','RSA Ireland'),
             ('http://nl.rsagroup.com','RSA Nederland'),
             ('https://www.codanforsikring.no','Codan Forsikring'),
             ('https://www.alahliarsa.com','Al Ahlia'),
             ('http://www.alamiyainsurance.com.sa','Al Alamiya'),
             ('http://es.rsagroup.com','RSA España'),
             ('https://www.trygghansa.se','Trygg-Hansas '),
             ('https://www.rsadirect.ae','RSA Dubai'),
             ('https://www.morethan.com','MORE TH>N'),
             ('https://www.rsabroker.com/home','RSA Broker'),
             ('https://www.motability.rsagroup.co.uk','RSA Motability'), ]

    METRICS = [('lighthouse',
                'Lighthouse analyzes web apps and web pages, collecting modern performance metrics and insights on developer best practices.'),
               ('keywords', 'RAKE based keyword extractor')]

    def initial_pages(apps, schema_editor):
        pass

    def initial_metrics(apps, schema_editor):
        pass

    dependencies = [
        ('metricsapp', '0003_auto_20180528_1225'),
    ]

    operations = [
        migrations.RunPython(initial_pages),
        migrations.RunPython(initial_metrics),
    ]
